<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">
                    Admin
                </div>
                <div class="panel-body">
                    Bem vindo <b><?=$this->view->email ?></b>
                </div>
            </div>
        </div>
    </div>
</div>

