<!-- Main component for a primary marketing message or call to action -->
<div class="jumbotron">
    <h1><img src="../../assets/images/miniLogo.png">CodeAndCode</h1>
    <p></p>
    <p>
        <a class="btn btn btn-primary" href="/" role="button">Ver docs &raquo;</a>
    </p>

    <div class="mastfoot">
        <div class="inner">
            <p>code by <a href="http://www.codeandcode.com.br">{Code and Code }</a></p>
        </div>
    </div>

</div>


