<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="icon" href="../../assets/images/miniLogo.png">

    <title>{CodeAndCode}</title>

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="../../assets/css/bootstrap.min.css">
    <link rel="stylesheet" href="../../assets/css/bootstrap-theme.css">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700" rel="stylesheet" type="text/css">

</head>
<body id="app-layout">

<div class="container">

    <div class="jumbotron">
        <h1>Ops :(</h1>
        <p> {msg}</p>
        <p></p>
        <p>
            <button class="btn btn btn-primary" type='button' onclick='javascript:history.back();self.location.reload();'>Voltar</button>
        </p>
    </div>

</div> <!-- /container -->

</body>
</html>





